jobs:
  include:
    - name: "Backend"
      python: 3.8
      language: python
      services:
        - postgresql
      install:
        - pipenv install
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
      script:
        - python manage.py test
      after_success:
        - test $TRAVIS_BRANCH = "master" && zappa update dev && zappa manage dev migrate
    - name: "Frontend"
      python: 3.8
      language: python
      services:
        - postgresql
      before_install:
        - psql -c 'create database travis_ci_test;' -U postgres
        - pipenv install
        - python manage.py runserver &
        - python manage.py migrate
      install:
        - cd frontend
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
        - nvm install 12.16.3
        - nvm use 12.16.3
        - npm install -g travis-ci-cloudfront-invalidation
        - npm install
      script:
        - npm test
        - npm run cy:test
        - npm run build
      deploy:
        on:
          branch: master
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: smartemr
        skip_cleanup: true
        local_dir: build
      after_deploy:
        - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST